services:
  app:
    build: .
    container_name: franmax_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./uploads:/var/www/html/uploads
    environment:
      # Pass-through to PHP container
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - DB_NAME=${DB_NAME:-franmaxindia}
    depends_on:
      - db

  db:
    image: mariadb:10.3
    container_name: franmax_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_NAME:-franmaxindia}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: franmax_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD:-root}
      - UPLOAD_LIMIT=256M
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
